apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: hadoop-datanode
  namespace: hadoop
spec:
  selector:
    matchLabels:
      app: hadoop-datanode
  template:
    metadata:
      labels:
        app: hadoop-datanode
    spec:
      containers:
      - name: datanode
        image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
        ports:
        - containerPort: 9864
        - containerPort: 9866
        - containerPort: 9867
        env:
        - name: CORE_CONF_fs_defaultFS
          value: "hdfs://hadoop-namenode:9000"
        - name: CORE_CONF_hadoop_http_staticuser_user
          value: "root"
        - name: CORE_CONF_hadoop_proxyuser_hue_hosts
          value: "*"
        - name: CORE_CONF_hadoop_proxyuser_hue_groups
          value: "*"
        - name: HDFS_CONF_dfs_webhdfs_enabled
          value: "true"
        - name: HDFS_CONF_dfs_permissions_enabled
          value: "false"
        - name: HDFS_CONF_dfs_replication
          value: "1"
        # Quan trọng: Sử dụng IP thay vì hostname
        - name: HDFS_CONF_dfs_datanode_use_datanode_hostname
          value: "false"
        - name: HDFS_CONF_dfs_client_use_datanode_hostname
          value: "false"
        - name: HDFS_CONF_dfs_datanode_hostname
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: HDFS_CONF_dfs_datanode_address
          value: "0.0.0.0:9866"
        - name: HDFS_CONF_dfs_datanode_http_address
          value: "0.0.0.0:9864"
        - name: HDFS_CONF_dfs_datanode_ipc_address
          value: "0.0.0.0:9867"
        - name: HDFS_CONF_dfs_namenode_datanode_registration_ip___hostname___check
          value: "false"
        volumeMounts:
        - name: datanode-storage
          mountPath: /hadoop/dfs/data
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
      volumes:
      - name: datanode-storage
        hostPath:
          path: /tmp/hadoop/datanode
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: hadoop-datanode
  namespace: hadoop
spec:
  selector:
    app: hadoop-datanode
  ports:
  - name: datanode-web
    port: 9864
    targetPort: 9864
  - name: datanode-data
    port: 9866
    targetPort: 9866
  - name: datanode-ipc
    port: 9867
    targetPort: 9867
  type: ClusterIP